#!/bin/bash
set -e

CONFIG_FILE="/config/config.py"

# Wait for config to be generated by access-bot on first run
echo "Waiting for config file..."
until [ -f "$CONFIG_FILE" ]; do
    sleep 2
done

echo "Starting mtprotoproxy..."
exec mtprotoproxy "$CONFIG_FILE"
